---
- name: Export Controller
  hosts: localhost
  connection: local 
  gather_facts: False

  tasks:
    - name: Export all assets
      ansible.controller.export:
        all: True
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: export_results

    - debug:
        var: export_results

    - name: Export assets to a file
      delegate_to: "{{controller_host1}}"
      copy:
        content: "{{ export_results | to_nice_yaml( width=50, explicit_start=True, explicit_end=True) }}"
        dest: ~controller_assets.yaml
