---
- name: Export Controller 1 & Import into Controller 2
  hosts: localhost
  connection: local 
  gather_facts: False
  environment: 
    CONTROLLER_OPTIONAL_API_URLPATTERN_PREFIX: '/api/controller/'

  tasks:
    - name: Export all assets
      awx.awx.export:
        all: True
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_config

    - name: Import Controller Assets
      awx.awx.import:
        assets: "{{ controller_config.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False