---
- name: Import Controller Configs
  hosts: localhost
  connection: local 
  gather_facts: false

  tasks:
    - name: Export Controller Projects
      ansible.controller.export:
        projects: 'all'
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_projects

    - name: Import Controller Projects
      ansible.controller.import:
        assets: "{{ controller_projects.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False
