---
- name: Import Controller Configs
  hosts: localhost
  connection: local 
  gather_facts: false

  tasks:
    - name: Export Controller Notification Templates
      ansible.controller.export:
        notification_templates: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_notification_templates
      tags: Notification Templates
   
    - name: Import Controller Notification Templates
      ansible.controller.import:
        assets: "{{ controller_notification_templates.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False
      tags: Notification Templates

    - name: Export Controller Execution Environments
      ansible.controller.export:
        execution_environments: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_execution_environments
      tags: Execution Environments

    - name: Import Controller Execution Environments
      ansible.controller.import:
        assets: "{{ controller_execution_environments.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False
      tags: Execution Environments

    # - name: Export Controller Organizations
    #   ansible.controller.export:
    #     organizations: ['all']
    #     controller_host: "{{controller_host1}}"
    #     controller_oauthtoken: "{{controller_token1}}"
    #     validate_certs: False
    #   register: controller_organizations
    #   tags: Organizations

    # - name: Import Controller Organizations
    #   ansible.controller.import:
    #     assets: "{{ controller_organizations.assets }}"
    #     controller_host: "{{controller_host2}}"
    #     controller_oauthtoken: "{{controller_token2}}"
    #     validate_certs: False
    #   tags: Organizations

    # - name: Export Controller Teams
    #   ansible.controller.export:
    #     teams: ['all']
    #     controller_host: "{{controller_host1}}"
    #     controller_oauthtoken: "{{controller_token1}}"
    #     validate_certs: False
    #   register: controller_teams
    #   tags: Teams
   
    # - name: Import Controller Teams
    #   ansible.controller.import:
    #     assets: "{{ controller_teams.assets }}"
    #     controller_host: "{{controller_host2}}"
    #     controller_oauthtoken: "{{controller_token2}}"
    #     validate_certs: False
    #   tags: Teams

    # - name: Export Controller Users
    #   ansible.controller.export:
    #     users: ['all']
    #     controller_host: "{{controller_host1}}"
    #     controller_oauthtoken: "{{controller_token1}}"
    #     validate_certs: False
    #   register: controller_users
    #   tags: Users
   
    # - name: Import Controller Users
    #   ansible.controller.import:
    #     assets: "{{ controller_users.assets }}"
    #     controller_host: "{{controller_host2}}"
    #     controller_oauthtoken: "{{controller_token2}}"
    #     validate_certs: False
    #   tags: Users

    - name: Export Controller Credential Types
      ansible.controller.export:
        credential_types: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_credential_types
      tags: Credential Types
   
    - name: Import Controller Credential Types
      ansible.controller.import:
        assets: "{{ controller_credential_types.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False
      tags: Credential Types

    - name: Export Controller Credentials
      ansible.controller.export:
        credentials: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_credentials
      tags: Credentials

    - name: Import Controller Credentials
      ansible.controller.import:
        assets: "{{ controller_credentials.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False
      tags: Credentials

    - name: Export Controller Projects
      ansible.controller.export:
        projects: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_projects
      tags: Projects

    - name: Import Controller Projects
      ansible.controller.import:
        assets: "{{ controller_projects.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False
      tags: Projects

    - name: Export Controller Inventory
      ansible.controller.export:
        inventory: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_inventory
      tags: Inventory

    - name: Import Controller Inventory
      ansible.controller.import:
        assets: "{{ controller_inventory.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False
      tags: Inventory

    - name: Export Controller Inventory Sources
      ansible.controller.export:
        inventory_sources: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_inventory_sources
      tags: Inventory Sources

    - name: Import Controller Inventory Sources
      ansible.controller.import:
        assets: "{{ controller_inventory_sources.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False
      tags: Inventory Sources

    - name: Export Controller Job Templates
      ansible.controller.export:
        job_templates: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_job_templates
      tags: Job Templates

    - name: Import Controller Job Templates
      ansible.controller.import:
        assets: "{{ controller_job_templates.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False
      tags: Job Templates
    
    - name: Export Controller Workflow Job Templates
      ansible.controller.export:
        workflow_job_templates: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_workflow_job_templates
      tags: Workflow Job Templates
   
    - name: Import Controller Workflow Job Templates
      ansible.controller.import:
        assets: "{{ controller_workflow_job_templates.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False
      tags: Workflow Job Templates
