---
- name: Import Controller Configs
  hosts: localhost
  connection: local 
  gather_facts: false

  tasks:
    - name: Export Controller Credential Types
      awx.awx.export:
        credential_types: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_credential_types
   
    - name: Import Controller Credential Types
      awx.awx.import:
        assets: "{{ controller_credential_types.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False

    - name: Export Controller Notification Templates
      awx.awx.export:
        notification_templates: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_notification_templates
   
    - name: Import Controller Notification Templates
      awx.awx.import:
        assets: "{{ controller_notification_templates.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False

    - name: Export Controller Execution Environments
      awx.awx.export:
        execution_environments: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_execution_environments

    - name: Import Controller Execution Environments
      awx.awx.import:
        assets: "{{ controller_execution_environments.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False

    - name: Export Controller Organizations
      awx.awx.export:
        organizations: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_organizations

    - name: Import Controller Organizations
      awx.awx.import:
        assets: "{{ controller_organizations.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False

    - name: Export Controller Credentials
      awx.awx.export:
        credentials: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_credentials

    - name: Import Controller Credentials
      awx.awx.import:
        assets: "{{ controller_credentials.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False

    - name: Export Controller Projects
      awx.awx.export:
        projects: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_projects

    - name: Import Controller Projects
      awx.awx.import:
        assets: "{{ controller_projects.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False

    - name: Export Controller Inventory
      awx.awx.export:
        inventory: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_inventory

    - name: Import Controller Inventory
      awx.awx.import:
        assets: "{{ controller_inventory.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False

    - name: Export Controller Inventory Sources
      awx.awx.export:
        inventory_sources: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_inventory_sources

    - name: Import Controller Inventory Sources
      awx.awx.import:
        assets: "{{ controller_inventory_sources.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False

    - name: Export Controller Job Templates
      awx.awx.export:
        job_templates: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_job_templates

    - name: Import Controller Job Templates
      awx.awx.import:
        assets: "{{ controller_job_templates.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False
    
    - name: Export Controller Workflow Job Templates
      awx.awx.export:
        workflow_job_templates: ['all']
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      register: controller_workflow_job_templates
   
    - name: Import Controller Workflow Job Templates
      awx.awx.import:
        assets: "{{ controller_workflow_job_templates.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False
